### PR TITLE
New heroes have been released. Zul'jin is in this week's rotation, so…

### PR DESCRIPTION
**Pull request by kalebhermes**
… our script needed to be updated. Added support for Zul'jin, Valeera and Lucio.

### CODE REVIEW

**Comment by kalebhermes** [comment]
I added files here that weren't supposed to be. Let me remove them.

**Comment by kalebhermes** [comment]
Pushed a new patch. Should be good now.

**Review by yuna9 — APPROVED** [review]
:package: :ship: :moneybag:

And rebase if you don't mind.

**Comment by yuna9** [comment]
Never mind, it's one commit. 😄

**Pull request merged**
